feat: redesign 'add text' modal
graasp/graasp-builder pull request #1117
Opened 2024-03-27 14:37 UTC by ztlee042

#1096

2024-04-03 04:50 UTC, spaenleh requested changes
Looks good, I have a few comments, but overall I think it is very good !

2024-04-03 09:30 UTC, ztlee042 commented on src/components/item/form/DocumentForm.tsx
> +  };
Yes, it’s a bit different. The colors from palette are bit too dark as background colors. So I get these colors from the design file.

2024-04-03 14:27 UTC, spaenleh approved these changes
Changes look good as far as I am concerned. I think we need to merge the fonts and typography variants before this PR.

2024-04-04 08:35 UTC, pyphilia approved these changes
Thanks for this PR! I've left some suggestions, let me know if you have questions.

2024-04-04 08:35 UTC, pyphilia commented on src/langs/en.json
> +  "CREATE_NEW_ITEM_NAME_HELPER_TEXT": "Show in the builder",
```suggestion
  "CREATE_NEW_ITEM_NAME_HELPER_TEXT": "Show in Graasp Builder",
```

2024-04-04 08:35 UTC, pyphilia commented on src/langs/en.json
> +  "CREATE_NEW_ITEM_DISPLAY_NAME_HELPER_TEXT": "Show in the player. Defaults to the 'Name' field. Customize it to your needs.",
```suggestion
  "CREATE_NEW_ITEM_DISPLAY_NAME_HELPER_TEXT": "Show in Graasp Player. Defaults to the 'Name' field. Customize it to your needs.",
```

2024-04-04 08:35 UTC, pyphilia commented on src/components/main/NewItemModal.tsx
> +            <Typography variant="h2" color="primary">
I would let it untouched, or you change all the others. But in any case I think h2 is way too big.

2024-04-04 12:23 UTC, ztlee042 commented
![CleanShot 2024-04-04 at 14 20 25](https://github.com/graasp/graasp-builder/assets/31677780/cd70a204-9e18-4136-aecb-14fb1c1cca47)
# Fix Select

- Add icons
- Apply colors via theme 
- Select 'standard' by default

# Future work
- Change the hover color on the selected item, current one is a purple-ish color, which is not consistent with the gray-ish color on unselected items
- Align the select, menu items with the text area

2024-04-04 12:55 UTC, ztlee042 commented
# Add Tooltip

- move helper text to tooltip
- remove the built-in required feature since it takes another row instead on the same row with the new label
- add a custom required start
![CleanShot 2024-04-04 at 14 53 45](https://github.com/graasp/graasp-builder/assets/31677780/10549525-094f-4c65-a07a-67bf640425cb)

2024-04-04 15:23 UTC, pyphilia approved these changes
All good to me, you just need to rebase and we can merge this branch.

2024-04-04 15:23 UTC, pyphilia commented on src/langs/en.json
> +  "CREATE_NEW_ITEM_DISPLAY_NAME_HELPER_TEXT": "Show in Graasp player. Defaults to the 'Name' field. Customize it to your needs.",
```suggestion
  "CREATE_NEW_ITEM_DISPLAY_NAME_HELPER_TEXT": "Show in Graasp Player. Defaults to the 'Name' field. Customize it to your needs.",
```

2024-04-04 15:36 UTC, pyphilia requested changes

2024-04-04 15:36 UTC, pyphilia commented on src/components/item/form/DocumentForm.tsx
> +        <DisplayNameForm
Actually the display name is on autoFocus. I think it's the `name` field that should be focused by default.

2024-04-04 16:08 UTC, ztlee042 commented
> All good to me, you just need to rebase and we can merge this branch.

I rebased, hope I get it right :)

2024-04-05 13:04 UTC, pyphilia approved these changes

2024-04-05 13:26 UTC, merged