feat: delete item thumbnail
graasp/graasp-builder pull request #1168
Opened 2024-04-18 13:57 UTC by LinaYahya

closes #1155

2024-04-19 13:50 UTC, pyphilia commented on src/components/item/settings/ThumbnailWithDeleteButton.tsx
> +  const [isHovered, setIsHovered] = useState(false); // State to manage hover
```suggestion
  const [isHovered, setIsHovered] = useState(false);
```

2024-04-22 09:18 UTC, LinaYahya commented on package.json
> +    "@graasp/query-client": "https://github.com/graasp/graasp-query-client.git#763-delete-thumbnail-query",
I'll update after the new release :)

2024-04-23 06:48 UTC, pyphilia requested changes
Just a change for a test, and update the yarn lock, and that should be good!

2024-04-23 06:48 UTC, pyphilia commented on cypress/e2e/item/settings/thumbnail.cy.ts
> +      cy.get(`#${ITEM_THUMBNAIL_CONTAINER_ID}`).trigger('mouseover');
You told me this doesn't work right? If you use `.invoke('show')` on a button that does not exist, does that throw? maybe you could catch that so you know the button does not exist.

2024-04-23 09:24 UTC, merged