fix: improve settings page and overall
graasp/graasp-builder pull request #1184
Opened 2024-04-24 14:47 UTC by spaenleh

2024-04-25 13:03 UTC, pyphilia requested changes
I'm not fan of this "3 options" empty content. What about removing the browse files with new item? For me it makes no sense to have more than one button here. Or use this layout:
![image](https://github.com/graasp/graasp-builder/assets/11229627/ff49c444-fd57-47a9-9710-9b931f551de2)
![image](https://github.com/graasp/graasp-builder/assets/11229627/cbfaab0d-e744-452b-bf26-de4de2df289c)

Thanks for all the changes!!! 🍇

2024-04-25 13:03 UTC, pyphilia commented on package.json
> +    "@graasp/ui": "github:graasp/graasp-ui#update-table-for-background",
To update.

2024-04-25 13:03 UTC, pyphilia commented on src/components/item/publish/CustomizedTagsEdit.tsx
> +      // border="1px solid #ddd"
Remove?

2024-04-25 13:03 UTC, pyphilia commented on src/components/item/settings/ClearChatButton.tsx
> +          {}
?

2024-04-25 13:03 UTC, pyphilia commented on src/components/item/settings/GeolocationPicker.tsx
> +      // border="1px solid #ddd"
Remove?

2024-04-25 13:03 UTC, pyphilia commented on src/components/item/settings/ItemLicenseSettings.tsx
> +  // };
Remove?

2024-04-25 13:03 UTC, pyphilia commented on src/components/item/settings/ItemMetadataContent.tsx
> +    // bgcolor="white" borderRadius={2} border="1px solid #ddd"
Remove?

2024-04-25 13:03 UTC, pyphilia commented on src/langs/fr.json
> +  "ITEM_SETTINGS_GEOLOCATION_CLEAR": "Supprimer la Localisation Géolocalisation",
My bad.
```suggestion
  "ITEM_SETTINGS_GEOLOCATION_CLEAR": "Supprimer la Géolocalisation",
```

2024-04-25 13:38 UTC, ReidyT reviewed
Thanks for all these improvements, it looks nice !
 
I agree with Kim concerning the three options to add content on empty folder.
Also, I think it is a little weird the size of the language row comparing to the rest of the table. Maybe it could be nicer to have smaller `select` ? I have another comment about the select of the language who is not in the center of the row...

Except that, LGTM 👍

2024-04-25 20:27 UTC, spaenleh commented
@ReidyT see https://github.com/graasp/graasp-ui/pull/825 for the centering of the select :wink:

2024-04-25 20:39 UTC, spaenleh commented
@pyphilia @ReidyT How about this layout ?
<img width="888" alt="Screenshot 2024-04-25 at 22 36 47" src="https://github.com/graasp/graasp-builder/assets/39373170/64ebd8a6-ce3d-4e2d-a5f3-f30fb83ad6b3">

2024-04-26 05:24 UTC, ReidyT approved these changes
Yeah ! I really like the new empty box 👌

2024-04-26 05:24 UTC, ReidyT commented on package.json
> +    "@graasp/ui": "github:graasp/graasp-ui#remove-margin-when-no-label",
Just a reminder 😄

2024-04-26 08:27 UTC, pyphilia approved these changes

2024-04-26 09:16 UTC, merged