feat: allow user to request membership
graasp/graasp-builder pull request #1424
Opened 2024-08-27 16:35 UTC by pyphilia

close #1423

2024-08-30 14:02 UTC, pyphilia commented
<img width="1142" alt="Screenshot 2024-08-30 at 16 01 44" src="https://github.com/user-attachments/assets/d580d25e-e997-48cd-a712-865b8bef5a87">

2024-09-12 12:14 UTC, spaenleh submitted a review, later dismissed
Looks good to me ! I have added a few comments to improve some parts. Feel free to put them as issues if they are too large to handle in this PR. 

Great work on the refactoring of the code ! 💪

2024-09-13 06:54 UTC, ReidyT requested changes
Thanks for this PR, it's a great refactor 🙌 I agree with what Basile said and I also let a few comments. Except for that, it looks good to me 🤠

2024-09-13 06:54 UTC, ReidyT commented on cypress/e2e/item/authorization/itemLogin/itemLogin.cy.ts
> +      // use username to check no member id is incorrectly sent
Same question here

2024-09-13 06:54 UTC, ReidyT commented on cypress/e2e/item/authorization/itemLogin/itemLogin.cy.ts
> +    cy.click('iojwlmke');
I agree, it's not clear ^^

2024-09-13 06:54 UTC, ReidyT commented on cypress/e2e/item/authorization/itemLogin/itemLoginSetting.cy.ts
> +    expect(body?.type).to.equal(ItemLoginSchemaType.UsernameAndPassword);
Shouldn't the body type be equal to the new mode?

2024-09-13 06:54 UTC, ReidyT commented on cypress/e2e/item/authorization/itemLogin/itemLoginSetting.cy.ts
> +  disabled?: boolean;
What is the difference between `isEnabled = true` and `disabled = false`? To me, the two parameters represent the same thing 😅.

2024-09-13 06:54 UTC, ReidyT commented on src/components/pages/item/accessWrapper/RequestAccessContent.tsx
> +        {translateBuilder('Request access to this item')}
Use const here too

2024-09-13 06:54 UTC, ReidyT commented on src/components/pages/item/accessWrapper/RequestAccessContent.tsx
> +          : translateBuilder('Request access')}
Same here

2024-09-13 08:09 UTC, spaenleh commented on src/components/item/sharing/membershipTable/EditPermissionButton.tsx
> +          <Button
Ok so it is good !

2024-09-23 14:12 UTC, merged