feat(deps): migrate react query v5
graasp/graasp-builder pull request #1446
Opened 2024-09-13 09:27 UTC by ReidyT

2024-09-18 15:52 UTC, pyphilia requested changes

2024-09-18 15:52 UTC, pyphilia commented on cypress/e2e/item/settings/thumbnail.cy.ts
> +    it.only(`upload item thumbnail`, () => {
Remove.

2024-09-18 15:52 UTC, pyphilia commented on package.json
> +    "@graasp/query-client": "github:graasp/graasp-query-client#889-migrate-to-v5",
Reminder!

2024-09-30 12:31 UTC, spaenleh approved these changes
Looks good ! Just out of curiosity, we do not need to change the usage of `initialIsLoading` ?

2024-09-30 12:40 UTC, ReidyT commented
> Looks good ! Just out of curiosity, we do not need to change the usage of `initialIsLoading` ?

No you're right, I forgot this! Thanks for your comment!

2024-09-30 12:43 UTC, spaenleh approved these changes
Very nice !

2024-10-02 08:43 UTC, pyphilia approved these changes
LGTM 🥾

2024-10-02 10:44 UTC, merged