466 workflow update
graasp/graasp-builder pull request #468
Opened 2022-10-25 12:17 UTC by pyphilia

This PR fixes some issues, and prevent type checking by react.
Instead `tsc` will type check, which should use node's `max old size`.

close #466

2022-10-25 12:45 UTC, spaenleh requested changes
🪆 Looks good, I have added some comments and suggestions

2022-10-25 12:45 UTC, spaenleh commented on .husky/pre-push
> +npx tsc --noEmit
Is there a particular reason why we would use `npx` here instead of `yarn` ?

2022-10-25 12:45 UTC, spaenleh commented on package.json
> +    "pre-commit": "npx tsc --noEmit && yarn prettier:check && yarn lint",
I think this should go in a `.husky/pre-commit` file with the following content:

```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx tsc --noEmit && yarn prettier:check && yarn lint
```

2022-10-25 12:45 UTC, spaenleh commented on package.json
> +    "test:once": "env-cmd -f ./.env.test react-app-rewired test --watchAll=false",
Do we use these ? I think we only use cypress tests and not react-testing library, but i may be wrong.

2022-10-25 12:45 UTC, spaenleh commented on src/components/item/sharing/CreateItemMembershipForm.js
> +import { PERMISSION_LEVELS } from '../../../enums';
Use `@graasp/sdk` ?

2022-10-25 12:45 UTC, spaenleh commented on src/config/queryClient.js
> -  API_ROUTES,
Why the return to `js` in this case ?

2022-10-26 08:24 UTC, pyphilia commented on src/components/item/sharing/CreateItemMembershipForm.js
> +import { PERMISSION_LEVELS } from '../../../enums';
It's still a js file D: later...

2022-10-26 16:21 UTC, merged