ci: add auto-tag workflows
graasp/graasp-builder pull request #598
Opened 2023-03-20 12:29 UTC by spaenleh

2023-03-21 08:44 UTC, swouf approved these changes
As for the other PRs, let's merge 💯

2023-03-25 18:23 UTC, dialexo requested changes
I assume you will refactor with the extracted composite in graasp-deploy? 👍

2023-04-03 10:13 UTC, dialexo requested changes

2023-04-03 10:13 UTC, dialexo commented on .github/workflows/auto-tag.yml
> +name: Auto Tag
Do we also have a way to factor out this workflow?

2023-04-05 07:55 UTC, dialexo approved these changes

2023-04-05 09:09 UTC, merged