feat: add qr share link to share an item
graasp/graasp-builder pull request #797
Opened 2023-09-20 11:17 UTC by LinaYahya

add QR code to link sharing as follows
- having an icon of QR code 
![Screenshot from 2023-09-20 13-15-59](https://github.com/graasp/graasp-builder/assets/49619087/f0135534-e257-45f1-9b91-f52d01f11c70)

- open a modal of the generated QR Code
![Screenshot from 2023-09-20 13-16-11](https://github.com/graasp/graasp-builder/assets/49619087/5202cb55-27fc-4435-9933-199c774da919)

2023-09-22 11:19 UTC, pyphilia requested changes
Nice PR! I'm not quite sure about showing a bare modal with only the QR code, tho I can see the purpose of showing it big and alone. Most probably in the future we can extend the modal with a export as png button, etc.

2023-09-22 11:19 UTC, pyphilia commented on src/components/common/QRCode.tsx
> +  <Modal open={open} onClose={handleClose}>
It's best to use the Dialog component https://mui.com/material-ui/react-dialog/
instead of the bare Modal.

2023-09-22 11:19 UTC, pyphilia commented on src/components/common/QRCode.tsx
> +        style={{ height: 'auto', maxWidth: '100%', width: '100%' }}
What's `256`? Should it be factored out? Why do you need `width` as well?

2023-09-22 11:19 UTC, pyphilia commented on src/components/item/sharing/SharingLink.tsx
> +        <QRCode open={openQrModal} handleClose={closeQrModal} value={link} />
Would it make sense to create a `QrCodeButton` component that would contain 
```
<IconButton onClick={generateQrCode}>
              <QrCode2 />
            </IconButton>
```
and the modal?

2023-09-27 12:32 UTC, pyphilia requested changes
One last comment + it would be nice to have one test that click on this QR button and check the modal does open.

2023-09-27 12:32 UTC, pyphilia commented on src/components/common/QRCode.tsx
> +          <QR size={500} value={value} />
Why 500 now? Should this be a bit more responsive?

2023-10-02 11:46 UTC, spaenleh requested changes
🗳️ Nice changes ! Just a few comments and it is good to go.

2023-10-02 11:46 UTC, spaenleh commented on cypress/e2e/item/share/shareItem.cy.ts
> +    const item = SAMPLE_PUBLIC_ITEMS.items[0] as any;
You don't need this cast here. In general it is better to not cast to any when not necessary.

```suggestion
    const item = SAMPLE_PUBLIC_ITEMS.items[0];
```

2023-10-02 11:46 UTC, spaenleh commented on src/components/common/QRCode.tsx
> +          >
The `Box` component supports setting all sx props directly on itself:
```suggestion
          <Box width={{ xs: '60vw', sm: '50vw', md: '30vw', lg: '24vw' }}>
```

2023-10-02 11:46 UTC, spaenleh commented on src/components/item/sharing/SharingLink.tsx
> +          <span id={SHARE_ITEM_QR_BTN_ID}>
Why put the test id here and not directly on the IconButton ?

2023-10-02 12:46 UTC, spaenleh approved these changes

2023-10-02 13:59 UTC, merged