build: move menu items tree
graasp/graasp-builder pull request #910
Opened 2023-12-06 15:42 UTC by LinaYahya

Build move menu items tree to not using mui/ tree view, Basically the user will have a home as a root of the menu which contains own and shared items, 
For every folder that has children within there will be an arrow to let the user navigate to this item.  

![image](https://github.com/graasp/graasp-builder/assets/49619087/59d7952e-742a-4f75-b421-9128dff7d247)

2023-12-15 15:13 UTC, pyphilia requested changes
The modal tree is quite complex, I'd like more explanation and I'll review again. Thanks! 🎄

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/MoveTreeModal.tsx
> +      <DialogContent sx={{ height: '250px' }}>
Let's not fix the height. I notice you have the flickering with the width as well anyway.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/MoveTreeModal.tsx
> +            {paths.map((ele, index) => (
Use `parents` here.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/MoveTreeModal.tsx
> +  defaultParent,
Why can't this be called `parentItem`?

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/MoveTreeModal.tsx
> +  const [defaultSelectedSubItem, setDefaultSelectedSubItem] =
In this component, this doesn't need to be called `default`right?

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/MoveTreeModal.tsx
> +            ` to ${translateBuilder(BUILDER.HOME_TITLE)}`) ||
Let's translate `to` as well.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/MoveTreeModal.tsx
> +            (parentItem?.name && ` to ${parentItem?.name}`)}
Same comment as above.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/RowMenu.tsx
> +  return false;
You're disabling the option if the folder is a parent right? 
```suggestion
const itemPaths = itemIds.map((ele) => ele.replaceAll('_', '-'));
return itemPaths.some(item => item.path.includes(itemPath))
```
Be careful not to use `?.` everywhere, here you assume `itemPath` exist by typing it.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/RowMenu.tsx
> +      id={`${TREE_MODAL_MY_ITEMS_ID}-${ele.id}`}
Factor out in `selectors`.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/RowMenu.tsx
> +        marginBottom: '12px',
Can you use the `theme`?

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/RowMenu.tsx
> +        background: selectedId === ele.id ? 'rgba(80, 80, 210, 0.08)' : 'none',
Factor out the color.

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/RowMenu.tsx
> +          {true && (
Remove??

2023-12-15 15:13 UTC, pyphilia commented on src/components/main/RowMenu.tsx
> +                e.stopPropagation();
Remove?

2023-12-15 15:13 UTC, pyphilia commented on src/langs/en.json
> +  "EMPTY_FOLDER_CHILDREN_FOR_THIS_ITEM": "No Sub-Folders For this Item"
```suggestion
  "EMPTY_FOLDER_CHILDREN_FOR_THIS_ITEM": "This item does not contain any folder."
```

2023-12-21 12:21 UTC, LinaYahya commented on src/components/main/MoveTreeModal.tsx
> +    selectedId === TREE_MODAL_MY_ITEMS_ID ? '' : selectedId,
`useItem` only receive string or undefined

2023-12-21 12:24 UTC, LinaYahya commented on src/components/main/MoveTreeModal.tsx
> +  const [paths, setPaths] = useState<DiscriminatedItem[]>([]);
I don't prefer to useParents as I have a custom items such as `root` and `home`, and there's a case's that might not connected to the first parent, as an example when we want to move item from nested parent

2023-12-21 13:33 UTC, LinaYahya commented on src/components/common/MoveButton.tsx
> +    };
this case will not happen as there's always a value for place to move, But this is only as a kind of validation

2023-12-22 12:01 UTC, pyphilia requested changes

2023-12-26 10:12 UTC, LinaYahya commented on src/components/main/MoveTreeModal.tsx
> +                    setSelectedId('');
Actually the initial value is empty string So I'd prefer to keep it as it's default

2024-01-12 10:22 UTC, merged